### ISSUE TITLE
Retirar o footer. 

### ISSUE THREAD

**Issue by JCDMeira** [marcelluscaio/HTMLiceu#1]
Vi não tem nada no footer, e quanto a estilo só vi o reset chamando. Existe um principio da chamado yagni "You aren't gonna need it". que diz que você não deve adicionar nada no seu código que não vá usar. Isso é consumo computacional atoa, o site precisa criar uma tag html que não tem uso. Apesar de ser só uma tag, ainda é energia de processamento gasta atoa.

**Comment by marcelluscaio** [comment]
Muito obrigado pelo feedback, Jean! Alteração implementada. Criei um footer.
